ログインログアウト機能を実装しました
shinonome-inc/backend-final-assignment-hana pull request #2
Opened 2023-03-02 07:38 UTC by SShizawa

2023-03-03 06:34 UTC, SShizawa commented on accounts/tests.py
> +        )
assertEqualで統一した際にエラーが出たので、assertinで書きました。

2023-03-03 06:35 UTC, yodapuuu commented on accounts/tests.py
> +        )
どのコードでエラーがでたか教えていただいてもいいですか？

2023-03-03 06:38 UTC, yodapuuu commented on accounts/tests.py
> +        )
統一した際のコードと出たエラーの画面のスクショがあるとありがたいです！

2023-03-03 06:47 UTC, SShizawa commented on accounts/tests.py
> +        )
<img width="1042" alt="assert" src="https://user-images.githubusercontent.com/117734671/222650642-61a50f96-3937-4a23-a198-eed454366e33.png">
↑こうなりました

2023-03-03 06:54 UTC, yodapuuu commented on accounts/tests.py
> +        )
分かりにくい指摘でごめんなさい、、セッションキーはself.assertInで大丈夫です！**エラーメッセージのテスト**のところだけ統一してくれればオッケーです。なのでざっと見た感じaccounts/test.pyの114行目、129行目、144行目、160行目、175行目、190行目をself.assertEqualで統一してください！

2023-03-03 12:27 UTC, yodapuuu commented
LGTM！

2023-03-05 09:04 UTC, gaato requested changes
ほぼ完璧です！細かいですが１点だけコメントしました。

2023-03-05 09:07 UTC, gaato commented on accounts/views.py
> +    template_name = "accounts/login.html"
一応これは `LOGOUT_REDIRECT_URL` は関係なくて `LogoutView` は画面が存在しないので template を指定する必要がないという方が正解です。

2023-03-05 09:23 UTC, gaato commented
追加で１点だけ！
今回の PR では未変更箇所なのでコメントできませんでしたがサインアップの View とテストでは `tweets:home` を直接していするのではなく `LOGIN_REDIRECT_URL` を使ったほうが良いと思います。

2023-03-05 14:19 UTC, gaato commented
LGTM！

2023-03-05 14:19 UTC, gaato approved these changes

2023-03-05 14:19 UTC, merged