ログイン・ログアウト機能実装
shinonome-inc/backend-final-assignment-hana pull request #3
Opened 2023-03-08 00:38 UTC by SShizawa

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-03-08 06:00 UTC, YusukeKaneko commented on accounts/tests.py
> +        )
こちらでuser2を作成している意図は何ですか？

2023-03-08 06:00 UTC, YusukeKaneko commented on accounts/views.py
> +# from .models import Tweet
もし不要であれば削除しましょう（他の部分も同様）。

2023-03-08 06:00 UTC, YusukeKaneko commented on tweets/views.py
> +    # queryset = model.objects.select_related("user")
```suggestion
    queryset = model.objects.select_related("user")
```
のようにコメント化を解除することで最適化できると思います。

2023-03-08 06:00 UTC, YusukeKaneko commented on tweets/views.py
> +    # queryset = Tweet.objects.select_related("user")
同様の指摘です。

2023-03-08 06:00 UTC, YusukeKaneko commented on tweets/views.py
> +    success_url = reverse_lazy("tweets:home")
```suggestion
    success_url = reverse_lazy("tweets:home")
    queryset = model.objects.select_related("user")
```
とすると最適化できると思います。

2023-03-08 11:14 UTC, SShizawa commented on accounts/tests.py
> +        )
意図はありません。
削除しても問題なく動いたので削除しました。

2023-03-08 13:22 UTC, YusukeKaneko commented on tweets/views.py
> +    queryset = Tweet.objects.select_related("user")
細かいですが、ここは
```suggestion
    queryset = model.objects.select_related("user")
```
とすると統一感が合ってよいと思います。

2023-03-08 13:22 UTC, YusukeKaneko commented
adminに`Tweet`モデルを登録するようお願いします。

2023-03-09 02:25 UTC, Akinori13 requested changes
非常にいい感じです！少しコメントしました！

2023-03-09 02:25 UTC, Akinori13 commented on accounts/views.py
> +        return super().get_context_data(**kwargs)
これ必要です？

2023-03-09 02:25 UTC, Akinori13 commented on tweets/tests.py
>      def test_failure_post_with_not_exist_tweet(self):
DBのデータが削除されていないことを確認しましょう！

2023-03-09 02:25 UTC, Akinori13 commented on tweets/tests.py
>      def test_failure_post_with_incorrect_user(self):
ここも削除されていないことを確認しましょう！

2023-03-09 11:37 UTC, SShizawa commented on tweets/tests.py
>      def test_failure_post_with_not_exist_tweet(self):
DBのデータが削除されていないことは、どのように確認すればよいのでしょうか。

2023-03-09 14:12 UTC, Akinori13 commented on tweets/tests.py
>      def test_failure_post_with_not_exist_tweet(self):
exists()メソッドを使いましょう！！

2023-03-10 12:14 UTC, SShizawa commented on tweets/tests.py
>      def test_failure_post_with_not_exist_tweet(self):
assertTrueを使う感じですか？
実行したらエラーが出たのでました

2023-03-11 01:08 UTC, TAK848 commented on tweets/tests.py
>      def test_failure_post_with_not_exist_tweet(self):
これでいいとおもう

2023-03-11 01:08 UTC, TAK848 approved these changes
LGTM

2023-03-11 01:08 UTC, merged