フォロー機能実装（１）
shinonome-inc/backend-final-assignment-hana pull request #4
Opened 2023-03-15 09:41 UTC by SShizawa

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-03-17 17:48 UTC, yodapuuu reviewed
いい感じです！
N+1問題が起きているか確認する際にdjangoのdebugtoolbarを使うことを推奨しています。contextの中身はどんなのを渡せているかを確認できるのでぜひ数行書き入れてみてください。

2023-03-17 17:48 UTC, yodapuuu commented on accounts/models.py
> +    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follower")
related_nameなのですが逆の方がいいです。followingに対してfollower,また逆も然りという感じです。
related_nameをつけるとUser.(related_name)などで呼び出すことができるようになります。ちょっと説明が雑なので申し訳ないのですが以下のサイトのリンクを添付しておきます。

https://djangobrothers.com/blogs/related_name/

2023-03-20 03:21 UTC, yodapuuu reviewed
こちらだけ修正お願いします。

2023-03-20 03:21 UTC, yodapuuu commented on templates/accounts/profile.html
> +{% elif isfollowing %}
着目点は間違っていないです！ただコーディングする際にみんなで守るルール的な役割のコーディング規則というものがあります。以下にリンクを添付しておきますが、今回はis_followingでもともとviewに記載されていた方にあわせるのがいいです。

https://qiita.com/naomi7325/items/4eb1d2a40277361e898b

2023-03-20 03:21 UTC, yodapuuu commented on accounts/views.py
> +        context["followings_num"] = FriendShip.objects.filter(follower=self.object).count()
こちらを"is_following"に合わせましょう。

2023-03-20 03:57 UTC, yodapuuu commented on accounts/models.py
> +    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
Userモデルを外部キーで持ってくる時にはUserモデルを引数に持ってくるのではなく、settings.AUTH_USER_MODELを使用してください。細かいことで申し訳ないのですがよろしくお願いします。

以下の公式ドキュメントをチェックしてください
https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#referencing-the-user-model

2023-03-20 04:13 UTC, yodapuuu commented
LGTM

2023-03-20 15:38 UTC, Akinori13 requested changes
良い感じです！少しだけコメントしました！

2023-03-20 15:38 UTC, Akinori13 commented on accounts/tests.py
>      def test_success_get(self):
フォローしている人数のカウントもアサーションしましょう

2023-03-21 03:22 UTC, Akinori13 requested changes
コメントしました！

2023-03-21 03:22 UTC, Akinori13 commented on accounts/tests.py
> +        self.assertEqual(follow_count, 1)
SQL発行しての確認ではなく、responseからアサーションしてください！

2023-03-21 14:18 UTC, SShizawa commented on accounts/tests.py
> +        self.assertEqual(follow_count, 1)
<img width="1059" alt="わからん" src="https://user-images.githubusercontent.com/117734671/226633225-5ebf819a-63f1-42f7-9e15-138ecc2b56c3.png">
self.assertEqual(response.objects.count(), 1)を加えた際に
'TemplateResponse' object has no attribute 'objects'というエラーが出ました。
responseでfollowlistを返すように設定したはずなのですが、followlistのカウントができない原因が分かりませんでした。

2023-03-21 14:31 UTC, Akinori13 commented on accounts/tests.py
> +        self.assertEqual(follow_count, 1)
文字通りresponseにはobjectsという属性がないというわけです。
response.content, response.contextなどを用いて確認してみましょう。

Viewsを通してDjangoは`context`に`Queryset`（データベースの結果）を渡し、`context`を`template`で展開しています。
具体的には、viewsで、以下のようにQuerysetが格納されます
```python
context["objects"]=Followership.objects.filter(followee=request.user)
```

そしてtemplateで展開されるわけです。
```html
{% for object in objects %}
{{ object }}
{% endfor %}
```

2023-03-22 02:19 UTC, Akinori13 commented
LGTM

2023-03-22 02:19 UTC, merged