一旦プッシュ
shinonome-inc/backend-final-assignment-hana pull request #5
Opened 2023-03-25 07:11 UTC by SShizawa

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-04-22 23:53 UTC, kotasuzuki72 requested changes

2023-04-22 23:53 UTC, kotasuzuki72 commented on templates/tweets/home.html
> +        data-is-liked="{% if tweet.pk in user_liked_list %}True{% else %}False{% endif %}" id="likebtn">
プロフィール画面においても、いいね・いいね取り消しボタンを作成してください。
具体的には、上記のbuttonタグをlike.htmlなどとして抜き出して、includeすると良いと思います。
また、下のscriptタグも抜き出してincludeする必要があると思います。

2023-04-22 23:53 UTC, kotasuzuki72 commented on templates/tweets/home.html
CSRF Tokenを使ってください。
参考：[https://docs.djangoproject.com/ja/4.1/howto/csrf/](url)

2023-04-22 23:53 UTC, kotasuzuki72 commented on templates/tweets/detail.html
>  <a href="{% url 'tweets:home' %}"><button type="button">ホームへ戻る</button></a>
この行があると、いいねが存在した時に、「ホームへ戻る」ボタンが2つ存在してしまうので、削除して下さい。

2023-04-23 07:57 UTC, kotasuzuki72 requested changes

2023-04-23 07:57 UTC, kotasuzuki72 commented on templates/accounts/profile.html
>  {% endblock %}
ホーム画面でいいねしたTweetを、プロフィール画面で見ると、
本来は「いいね解除」ボタンであるべきですが、
「いいね」ボタンが表示されてしまっています。
こちらの修正をしてください。

2023-04-23 12:01 UTC, kotasuzuki72 reviewed
先ほど指摘したプロフィール画面の挙動が修正できていていいと思います！
1点コメントしたので、確認お願いします。

2023-04-23 12:02 UTC, SShizawa commented on templates/tweets/like.html
> +<p>{{ user_liked_list }}</p>
消し忘れです！

2023-04-23 12:05 UTC, kotasuzuki72 commented on templates/tweets/like.html
> +<p>{{ user_liked_list }}</p>
分かりました。削除してから再度commitしてください。

2023-04-23 12:12 UTC, kotasuzuki72 approved these changes
LGTM

2023-04-23 13:50 UTC, masaya09 requested changes
N+1は[こちらの資料](https://shinonome-inc.notion.site/SQL-N-1-django-debug-toolbar-ac014e3601f741e3aa64fb0734bc5e95)を参考にして解決してみてください

2023-04-23 13:50 UTC, masaya09 commented on templates/scripts.html
> +                console.log(data)
console.logは削除

2023-04-23 13:50 UTC, masaya09 commented on tweets/views.py
> +        return JsonResponse(context)
contextで使用してるのはliked_countだけのようなので、それ以外は削除してOKです。
コメントアウトしてるところと、tweet_id = self.kwargs["pk"]は不要なので削除してください

2023-04-23 13:50 UTC, masaya09 commented on templates/base.html
> +    {% endblock %}
base.htmlでincludeするならblock js使う必要ないです。そのまま記述してしまって良いです。JSを用いたいところだけに記述したいならここは削除しましょう

2023-04-23 13:50 UTC, masaya09 commented on accounts/views.py
> +        user_like_list = (
51行目の記述は不要です。UserProfileViewがDetailViewを継承してるのと、model = User としてるのでself.objectで取ってこれています。

また、N+1問題が起きてるので解消してください

2023-04-23 13:50 UTC, masaya09 commented on tweets/views.py
> +    def get_context_data(self, **kwargs):
HomeViewでもN+1問題が起きてます

2023-04-24 17:26 UTC, masaya09 requested changes
django-debug-toolbarを用いてN+1が起きていないかを確認してみてください

2023-04-24 17:26 UTC, masaya09 commented on accounts/views.py
>          context["tweet_list"] = Tweet.objects.select_related("user").filter(user=self.object).order_by("-created_at")
user = self.objectとしたので、self.objectとしてるところは、userに変えましょう

2023-04-24 17:28 UTC, masaya09 requested changes

2023-04-24 17:28 UTC, masaya09 commented on templates/tweets/home.html
> +
base.htmlで読み込んでるので不要です

2023-04-24 17:28 UTC, masaya09 commented on templates/accounts/profile.html
> +    {% include 'tweets/like.html' %}
同様に不要

2023-04-24 20:46 UTC, SShizawa commented on templates/tweets/home.html
> +
scriptsとlikeボタンのhtmlをわけて書いたので必要だと思います！
ここでscriptsを読み込まないと、like ボタンが機能しません

2023-04-24 20:48 UTC, SShizawa commented
> 

<img width="887" alt="hom" src="https://user-images.githubusercontent.com/117734671/234113217-94e4b569-bc8b-43d1-804a-cfec4fdfd697.png">
自分で見た限りN+1問題は発生していませんでした。
添付したの画像はtwitter clineのhomeです

2023-04-24 21:53 UTC, masaya09 commented on templates/accounts/profile.html
> +    {% include 'tweets/like.html' %}
scripts.htmlと見間違えてました。完全にボケてましたね、すみません

2023-04-25 01:42 UTC, masaya09 requested changes

2023-04-25 01:42 UTC, masaya09 commented on templates/tweets/home.html
ツイート作成ボタンをホームに置いて欲しいです。現状だとツイート作成の導線がURLを直接叩かないといけなくなってます

2023-04-25 01:42 UTC, masaya09 commented on templates/tweets/home.html
また、ツイート投稿時にホームに表示される名前からその人のプロフィール画面に飛べるようにしてください

2023-04-25 01:42 UTC, masaya09 commented on templates/tweets/detail.html
ツイートを削除するボタンは必要です

2023-04-25 05:42 UTC, merged